# Generated by Django 5.1.7 on 2025-03-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessapp', '0002_remove_workout_date_remove_workout_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='tracked_weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Вес пользователя на момент тренировки'),
        ),
    ]
