# Generated by Django 5.1.7 on 2025-03-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessapp', '0003_workout_tracked_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='kilometers',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Километры'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='time_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Время (сек)'),
        ),
    ]
