# Generated by Django 5.1.7 on 2025-03-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessapp', '0004_exercise_kilometers_exercise_time_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='kilometers',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='time_seconds',
        ),
        migrations.AddField(
            model_name='exercise',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Дистанция (км)'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность (сек)'),
        ),
        migrations.AddField(
            model_name='exercisetype',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория'),
        ),
    ]
