# Generated by Django 5.1.7 on 2025-03-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessapp', '0005_remove_exercise_kilometers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к тренировке'),
        ),
    ]
