# Generated by Django 5.1.7 on 2025-03-29 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessapp', '0006_workout_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='comment',
        ),
    ]
