# Generated by Django 5.1.7 on 2025-03-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessapp', '0007_remove_workout_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='workout',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Оценка (0-10)'),
        ),
    ]
