# Generated by Django 5.1.7 on 2025-03-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessapp', '0008_workout_comment_workout_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Оценка тренировки в диапазоне от 1 до 5', null=True, verbose_name='Оценка'),
        ),
    ]
