# Generated by Django 5.1.7 on 2025-04-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessapp', '0009_alter_workout_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jarvisuser',
            name='age',
        ),
        migrations.AddField(
            model_name='jarvisuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
