# Generated by Django 5.1.7 on 2025-04-04 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessapp', '0010_remove_jarvisuser_age_jarvisuser_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jarvisuser',
            name='user_type',
            field=models.CharField(choices=[('client', 'Клиент'), ('trainer', 'Тренер')], default='client', max_length=15, verbose_name='Тип пользователя'),
        ),
        migrations.AddField(
            model_name='workout',
            name='is_trainer_created',
            field=models.BooleanField(default=False, verbose_name='Создано тренером'),
        ),
        migrations.AddField(
            model_name='workout',
            name='planned_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата для планирования'),
        ),
        migrations.AddField(
            model_name='workout',
            name='status',
            field=models.CharField(choices=[('created', 'Создано'), ('assigned', 'Назначено'), ('completed', 'Завершено')], default='completed', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='reps',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Повторения'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sets',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Подходы'),
        ),
        migrations.CreateModel(
            name='Approach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets_order', models.PositiveIntegerField(default=1, verbose_name='Номер подхода')),
                ('reps', models.PositiveIntegerField(default=0, verbose_name='Повторения')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Вес')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approaches', to='fitnessapp.exercise', verbose_name='Упражнение')),
            ],
        ),
    ]
