# Generated by Django 5.1.7 on 2025-04-07 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessapp', '0012_remove_jarvisuser_user_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_weight',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='sets',
        ),
        migrations.AddField(
            model_name='workout',
            name='planned_for',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата/время запланированной тренировки'),
        ),
        migrations.AddField(
            model_name='workout',
            name='status',
            field=models.CharField(choices=[('done', 'Завершена'), ('planned', 'Запланирована')], default='done', max_length=10, verbose_name='Статус тренировки'),
        ),
        migrations.CreateModel(
            name='ExerciseApproach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок подхода')),
                ('reps', models.PositiveIntegerField(default=0, verbose_name='Повторения')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Вес (кг)')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approaches', to='fitnessapp.exercise', verbose_name='Упражнение')),
            ],
        ),
    ]
